name: cmake win64 
            
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: testing
      run: |
        mkdir build;cd build
        # $winsdkinclude=
        cmake -DCMAKE_CXX_FLAGS=-I'D:/silver/qtcan/ci/pro" "files/more" "'spaces/$((ls 'D:/silver/qtcan/ci/pro" "files/more" "'spaces)[0].name) -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_BUILD_TYPE=Release -S ..

