name: cmake win64 
            
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: testing
      run: |
        choco install -y ninja
        mkdir build;cd build
        ls "C:/Program Files (x86)/Windows Kits/10/Include"
        $f="'"
        $r='"'
        $words=' '
        $words2=
        $winsdkinclude=
        cmake -G Ninja -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_FLAGS="`"-ID:/a/ci/ci/program files/more rspaces/$((ls 'D:/a/ci/ci/pro files/more spaces/')[0].name)`"" -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_BUILD_TYPE=Release -S ..
        ninja
        cd ..
        ./ci

