name: cmake win64 
            
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - name: installing more depens
      run: |
        pwd
        cd D:/a/ci/ci
        pwsh -c 'curl -L "https://github.com/openssl/openssl/releases/download/openssl-3.4.0/openssl-3.4.0.tar.gz" -o ossl.tar.gz'
        tar -xvzf ossl.tar.gz
        pwd
        ls
    - shell: msys2 {0}
      run: |
        cd "/d/a/ci/ci/openssl-3.4.0"
        pacman -S make
        export OPENSSL_USE_STATIC_LIBS=ON
        ./Configure --prefix=$PWD/dist no-idea no-mdc2 no-rc5 no-shared mingw64
        make depend && make && make install
