name: cmake win64 
            
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: testing
      run: |
        mkdir build;cd build
        ls "C:/Program Files (x86)/Windows Kits/10/Include"
        $f="'"
        $r='"'
        $words=' '
        $words2=$((ls 'D:/a/ci/ci/pro files/more spaces/')[0].name)
        $winsdkinclude=
        cmake -DCMAKE_CXX_FLAGS=$f-ID:/a/ci/ci/pro$r$words($r)files/more$r$words($r)rspaces/$words2$f -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_BUILD_TYPE=Release -S ..

